import { database } from '@/db/raw';
import { templates } from '@/lib/templates';
class InputError extends Error { constructor(message:string,public status=400){super(message)} }
function identity(r:Request){const id=r.headers.get('oai-authenticated-user-id');if(!id)throw new InputError('Please sign in to use your planner.',401);let name=r.headers.get('oai-authenticated-user-full-name')||r.headers.get('oai-authenticated-user-email')?.split('@')[0]||'You';if(r.headers.get('oai-authenticated-user-full-name-encoding')==='percent-encoded-utf-8')try{name=decodeURIComponent(name)}catch{}return {id,name};}
function str(v:unknown,max=120){if(typeof v!=='string')throw new InputError('Please check the form.');return v.trim().slice(0,max)}
async function membership(db:ReturnType<typeof database>,gid:string,uid:string){if(!await db.prepare('SELECT 1 FROM members WHERE group_id=? AND user_id=?').bind(gid,uid).first())throw new InputError('This gathering is not available to you.',403)}
function failure(e:unknown){if(e instanceof InputError)return Response.json({error:e.message},{status:e.status});console.error('Planner request failed',e);return Response.json({error:'Could not save or load your gathering. Please try again.'},{status:503})}
export async function GET(r:Request){try{const me=identity(r),db=database(),gid=new URL(r.url).searchParams.get('group');const groups=(await db.prepare('SELECT g.*, (SELECT COUNT(*) FROM members WHERE group_id=g.id) AS memberCount, (SELECT COUNT(*) FROM items WHERE group_id=g.id) AS itemCount, (SELECT COUNT(*) FROM items WHERE group_id=g.id AND assignee IS NOT NULL) AS assignedCount FROM gatherings g JOIN members m ON g.id=m.group_id WHERE m.user_id=? ORDER BY g.created_at DESC').bind(me.id).all()).results;if(!gid)return Response.json({me,groups},{headers:{'Cache-Control':'no-store'}});await membership(db,gid,me.id);const [memberRows,itemRows]=await Promise.all([db.prepare('SELECT user_id AS id,name FROM members WHERE group_id=? ORDER BY name').bind(gid).all(),db.prepare('SELECT * FROM items WHERE group_id=? ORDER BY created_at,id').bind(gid).all()]);return Response.json({me,groups,members:memberRows.results,items:itemRows.results},{headers:{'Cache-Control':'no-store'}})}catch(e){return failure(e)}}
export async function POST(r:Request){try{if(r.headers.get('origin')&&r.headers.get('origin')!==new URL(r.url).origin)throw new InputError('Invalid request origin.',403);const me=identity(r),db=database(),b=await r.json();if(b.action==='create'){const name=str(b.name),occasion=str(b.occasion);if(!name||!templates[occasion])throw new InputError('Choose a name and occasion.');const id=crypto.randomUUID(),code=crypto.randomUUID().replaceAll('-','').slice(0,12).toUpperCase();const seed=b.prefill?templates[occasion]:[];await db.batch([db.prepare('INSERT INTO gatherings (id,name,occasion,date,location,code,created_at) VALUES (?,?,?,?,?,?,?)').bind(id,name,occasion,str(b.date||''),str(b.location||''),code,Date.now()),db.prepare('INSERT INTO members (group_id,user_id,name) VALUES (?,?,?)').bind(id,me.id,me.name),...seed.map((i,n)=>db.prepare('INSERT INTO items (id,group_id,name,quantity,unit,category,created_at) VALUES (?,?,?,?,?,?,?)').bind(crypto.randomUUID(),id,i.name,i.quantity,i.unit,i.category,Date.now()+n))]);return Response.json({id})}
if(b.action==='join'){const code=str(b.code).toUpperCase().replaceAll(' ','');const group=await db.prepare('SELECT id FROM gatherings WHERE code=?').bind(code).first<{id:string}>();if(!group)throw new InputError('No gathering found. Double-check your invite code.',404);await db.prepare('INSERT OR IGNORE INTO members (group_id,user_id,name) VALUES (?,?,?)').bind(group.id,me.id,me.name).run();return Response.json({id:group.id})}
const gid=str(b.groupId);await membership(db,gid,me.id);
if(b.action==='saveItem'){const name=str(b.name),unit=str(b.unit,30),category=str(b.category),quantity=Number(b.quantity);if(!name||!unit||!Number.isFinite(quantity)||quantity<=0||quantity>1000000||!['Food','Drinks','Equipment','Essentials','Other'].includes(category))throw new InputError('Add a name, unit, category, and quantity above zero.');const assignee=b.assignee?str(b.assignee):null;if(assignee)await membership(db,gid,assignee);if(b.id){const result=await db.prepare('UPDATE items SET name=?,quantity=?,unit=?,category=?,assignee=?,note=?,packed=CASE WHEN ? IS NULL THEN 0 ELSE packed END WHERE id=? AND group_id=?').bind(name,quantity,unit,category,assignee,str(b.note||'',500),assignee,str(b.id),gid).run();if(!result.meta.changes)throw new InputError('This item was removed. Refresh your list.',409)}else await db.prepare('INSERT INTO items (id,group_id,name,quantity,unit,category,assignee,note,created_at) VALUES (?,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),gid,name,quantity,unit,category,assignee,str(b.note||'',500),Date.now()).run();}
else if(b.action==='deleteItem')await db.prepare('DELETE FROM items WHERE id=? AND group_id=?').bind(str(b.id),gid).run();
else if(b.action==='packed')await db.prepare('UPDATE items SET packed=? WHERE id=? AND group_id=? AND assignee IS NOT NULL').bind(b.packed?1:0,str(b.id),gid).run();
else if(b.action==='claim')await db.prepare('UPDATE items SET assignee=? WHERE id=? AND group_id=? AND assignee IS NULL').bind(me.id,str(b.id),gid).run();
else if(b.action==='template'){const seed=templates[str(b.occasion)];if(!seed)throw new InputError('Choose an occasion.');await db.batch(seed.map((i,n)=>db.prepare('INSERT INTO items (id,group_id,name,quantity,unit,category,created_at) VALUES (?,?,?,?,?,?,?)').bind(crypto.randomUUID(),gid,i.name,i.quantity,i.unit,i.category,Date.now()+n)));}
else if(b.action==='editGroup'){const name=str(b.name);if(!name)throw new InputError('Give your gathering a name.');await db.prepare('UPDATE gatherings SET name=?,date=?,location=? WHERE id=?').bind(name,str(b.date||''),str(b.location||''),gid).run();}
else throw new InputError('Unknown action.');return Response.json({ok:true});}catch(e){return failure(e)}}
