'use client';
import { useEffect,useRef,useState } from 'react';
import { ArrowLeft,ArrowRight,Plus,Users,Check,Package,ClipboardList,CalendarDays,MapPin,Link,Copy,Tent,PartyPopper,Flame,Utensils,Shapes,Pencil,Trash2,UserRound,CheckCheck,LoaderCircle,RefreshCw } from 'lucide-react';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from '@/components/ui/select';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Checkbox } from '@/components/ui/checkbox';
import { Progress } from '@/components/ui/progress';
import { AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogAction,AlertDialogCancel } from '@/components/ui/alert-dialog';
import { Toaster,toast } from 'sonner';
import { templates } from '@/lib/templates';
type Group={id:string;name:string;occasion:string;date:string;location:string;code:string;memberCount:number;itemCount:number;assignedCount:number;ownerId:string;memberPermission:string;visibility:string};
type Member={id:string;name:string};
type Item={id:string;name:string;quantity:number;unit:string;category:string;assignee:string|null;packed:number;note:string;myPacked:boolean;packedBy:string[]};
type Data={me:Member;groups:Group[];members?:Member[];items?:Item[]};
const icons={Camping:Tent,Party:PartyPopper,BBQ:Flame,Potluck:Utensils,Custom:Shapes};
const copy:Record<string,string>={Camping:'For a weekend under the stars.',Party:'Good people. Something to celebrate.',BBQ:'Fire up the grill. Share the prep.',Potluck:'Everyone brings something to the table.',Custom:'Your gathering, your list.'};
function OccasionIcon({name,size=22}:{name:string;size?:number}){const Icon=icons[name as keyof typeof icons]||Shapes;return <Icon size={size}/>}
function Picker({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:{value:string;label:string}[]}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="picker"><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>}
function dateLabel(v:string){return v?new Date(v+'T12:00:00').toLocaleDateString('en-CA',{month:'short',day:'numeric',year:'numeric'}):'Date to be decided'}
export default function Planner(){
 const [data,setData]=useState<Data|null>(null),[groupId,setGroupId]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[modal,setModal]=useState(''),[filter,setFilter]=useState('all'),[tab,setTab]=useState('items'),[deleting,setDeleting]=useState<Item|null>(null);
 const [groupForm,setGroupForm]=useState({name:'',occasion:'Camping',date:'',location:'',prefill:true,memberPermission:'edit',visibility:'public',password:''}),[joinCode,setJoinCode]=useState(''),[joinPassword,setJoinPassword]=useState(''),[template,setTemplate]=useState('Camping'),[formError,setFormError]=useState('');
 const [item,setItem]=useState({id:'',name:'',quantity:1,unit:'each',category:'Food',assignee:'none',note:''});
 const requestId=useRef(0);const active=useRef('');
 const group=data?.groups.find(g=>g.id===groupId),items=data?.items||[],members=data?.members||[];
 const isAdmin=!!group&&group.ownerId===data?.me.id,canEdit=!!group&&(isAdmin||group.memberPermission==='edit');
 async function load(id=active.current,quiet=false){const sequence=++requestId.current;if(!quiet)setLoading(true);try{const r=await fetch('/api/planner'+(id?'?group='+encodeURIComponent(id):''));const d=await r.json();if(!r.ok)throw Error(d.error);if(sequence===requestId.current){setData(d);setError('')}}catch(e){if(sequence===requestId.current&&!quiet)setError((e as Error).message)}finally{if(sequence===requestId.current&&!quiet)setLoading(false)}}
 useEffect(()=>{load('');const params=new URLSearchParams(location.search);if(params.get('join')){setJoinCode(params.get('join')!);setModal('join')}const timer=setInterval(()=>{if(!document.hidden)load(active.current,true)},15000);return()=>clearInterval(timer)},[]);
 function openGroup(id:string){active.current=id;setGroupId(id);setFilter('all');setTab('items');load(id)}
 function show(m:string){setFormError('');setModal(m)}
 async function mutate(body:Record<string,unknown>,success:string,close=true){if(busy)return;setBusy(true);setFormError('');try{const r=await fetch('/api/planner',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,groupId})});const result=await r.json();if(!r.ok)throw Error(result.error);if(close)setModal('');if(result.id)openGroup(result.id);else await load(active.current,true);toast.success(success);return true}catch(e){setFormError((e as Error).message);toast.error((e as Error).message);return false}finally{setBusy(false)}}
 function newGroup(occasion='Camping'){setGroupForm({name:'',occasion,date:'',location:'',prefill:occasion!=='Custom',memberPermission:'edit',visibility:'public',password:''});show('create')}
 function editItem(i?:Item){setItem(i?{...i,assignee:i.assignee||'none'}:{id:'',name:'',quantity:1,unit:'each',category:'Food',assignee:'none',note:''});show('item')}
 const assigned=items.filter(i=>i.assignee),unassigned=items.filter(i=>!i.assignee),packed=items.filter(i=>i.packed),mine=items.filter(i=>(i.assignee===data?.me.id||i.assignee==='everyone')),percent=items.length?Math.round(assigned.length/items.length*100):0;
 const visible=items.filter(i=>filter==='all'||filter==='unassigned'&&!i.assignee||filter==='assigned'&&i.assignee||filter==='mine'&&(i.assignee===data?.me.id||i.assignee==='everyone')||filter==='packed'&&i.packed);
 async function copyInvite(){try{await navigator.clipboard.writeText(location.origin+'/?join='+group?.code);toast.success('Invite link copied')}catch{toast.error('Copy the invite code below to share it.')}}
 return <div className="app"><Toaster position="bottom-center" richColors/>
 <header className="topbar"><button className="brand" onClick={()=>openGroup('')} aria-label="Bringalong home"><span className="brandmark"><Package size={23}/></span>bringalong<span className="brand-dot">.</span></button><div className="header-end"><span className="header-note">A little planning. A good time.</span><span className="avatar" title={data?.me.name||'Your profile'}>{data?.me.name?.[0]?.toUpperCase()||<UserRound size={18}/>}</span></div></header>
 <main>
 <div className="breadcrumb"><button onClick={()=>openGroup('')}>My gatherings</button>{group&&<><span>/</span><span>{group.name}</span></>}</div>
 {error?<section className="empty"><RefreshCw size={32}/><h1>Let’s try that again</h1><p>{error}</p><button className="btn primary" onClick={()=>load()}>Retry</button></section>:loading?<section className="empty" aria-live="polite"><LoaderCircle className="spin"/><p>Getting your plans together…</p></section>:!group?<>
 <section className="page-heading"><div><div className="eyebrow">LESS COORDINATING, MORE CONNECTING</div><h1>Good times start here<span>.</span></h1><p>Make a plan. Share the list. Everyone brings a little.</p></div><div className="actions"><button className="btn" onClick={()=>show('join')}><Link size={17}/>Join a gathering</button><button className="btn primary" onClick={()=>newGroup()}><Plus size={18}/>Create gathering</button></div></section>
 <div className="section-title"><h2>Your gatherings <span className="count">{data?.groups.length||0}</span></h2><span className="subtle">All your plans, in one place</span></div>
 {data?.groups.length?<div className="group-grid">{data.groups.map(g=><button className="group-card" key={g.id} onClick={()=>openGroup(g.id)}><div className="card-top"><span className={'occasion-icon '+g.occasion.toLowerCase()}><OccasionIcon name={g.occasion}/></span><span className="pill">{g.occasion}</span></div><h3>{g.name}</h3><p className="meta"><CalendarDays size={15}/>{dateLabel(g.date)}</p>{g.location&&<p className="meta"><MapPin size={15}/>{g.location}</p>}<div className="card-progress"><span>{g.assignedCount} of {g.itemCount} items assigned</span><Progress value={g.itemCount?g.assignedCount/g.itemCount*100:0}/></div><div className="card-bottom"><span><Users size={16}/>{g.memberCount} {g.memberCount===1?'person':'people'}</span><ArrowRight size={19}/></div></button>)}</div>:<section className="welcome-panel"><div className="empty-icon"><Users size={30}/></div><div><h2>Your next get-together starts with a list.</h2><p>Create your first gathering or join a friend’s with an invite code.</p><button className="text-button" onClick={()=>newGroup()}>Let’s make a plan <ArrowRight size={17}/></button></div><span className="welcome-number">01</span></section>}
 <section className="template-section"><div className="section-title"><div><h2>A head start for every occasion</h2><p className="subtle">Start with the essentials. Make the list your own.</p></div><span className="small-label">READY-TO-USE LISTS</span></div><div className="template-grid">{['Camping','Party','BBQ','Potluck'].map((t,n)=><button key={t} className={'template-card theme-'+n} onClick={()=>newGroup(t)}><div className="template-top"><OccasionIcon name={t} size={29}/><span className="round-arrow"><ArrowRight size={18}/></span></div><h3>{t==='Camping'?'Into the outdoors':t==='Party'?'Time to celebrate':t==='BBQ'?'Around the grill':'A seat at the table'}</h3><p>{copy[t]}</p><span className="template-foot">{t} <span>·</span> {templates[t].length} essentials</span></button>)}</div></section>
 </>:<>
 <button className="back-link" onClick={()=>openGroup('')}><ArrowLeft size={16}/>All gatherings</button>
 <section className="page-heading group-heading"><div className="gathering-title"><span className={'occasion-icon large '+group.occasion.toLowerCase()}><OccasionIcon name={group.occasion} size={29}/></span><div><span className="eyebrow">{group.occasion.toUpperCase()} TOGETHER</span><h1>{group.name}</h1><div className="event-meta"><span><CalendarDays size={16}/>{dateLabel(group.date)}</span>{group.location&&<span><MapPin size={16}/>{group.location}</span>}{isAdmin&&<button className="icon-button" aria-label="Edit gathering" onClick={()=>{setGroupForm({...group,prefill:false,password:''});show('editGroup')}}><Pencil size={15}/></button>}</div></div></div><button className="btn" onClick={()=>show('invite')}><Users size={17}/>Invite people</button></section>
 <section className="stats" aria-label="Gathering dashboard">{[{label:'On the list',value:items.length,icon:ClipboardList,f:'all',caption:'Everything you need'},{label:'Unassigned',value:unassigned.length,icon:UserRound,f:'unassigned',caption:'Waiting for a volunteer'},{label:'Assigned',value:assigned.length,icon:Users,f:'assigned',caption:'Someone’s got it covered'},{label:'Packed & ready',value:packed.length,icon:CheckCheck,f:'packed',caption:'One less thing to remember'}].map((s,n)=><button key={s.f} className={'stat '+(filter===s.f?'selected':'')} onClick={()=>{setFilter(s.f);setTab('items')}}><div className="stat-label">{s.label}<s.icon size={18}/></div><strong className={n===1&&s.value?'orange':''}>{s.value}</strong><span>{s.caption}</span></button>)}</section>
 <div className="detail-grid"><section className="list-panel"><Tabs value={tab} onValueChange={setTab}><div className="panel-head"><TabsList variant="line"><TabsTrigger value="items"><ClipboardList size={17}/>Packing list</TabsTrigger><TabsTrigger value="people"><Users size={17}/>People <span className="count">{members.length}</span></TabsTrigger></TabsList>{canEdit&&<button className="btn primary compact" onClick={()=>editItem()}><Plus size={17}/>Add item</button>}</div><TabsContent value="items"><div className="filters" aria-label="Filter items">{[['all','All items',items.length],['unassigned','Unassigned',unassigned.length],['mine','My items',mine.length]].map(([v,l,n])=><button key={v} className={filter===v?'active':''} aria-pressed={filter===v} onClick={()=>setFilter(String(v))}>{l}<span>{n}</span></button>)}{['assigned','packed'].includes(filter)&&<button className="active" onClick={()=>setFilter('all')}>{filter==='packed'?'Packed':'Assigned'} <span>×</span></button>}</div>
 {visible.length?<div className="items">{['Food','Drinks','Equipment','Essentials','Other'].map(category=>{const rows=visible.filter(i=>i.category===category);return rows.length?<section className="category" key={category}><h3>{category}<span>{rows.length}</span></h3>{rows.map(i=><div className={'item-row '+(i.packed?'is-packed':'')} key={i.id}><Checkbox className="pack-check" checked={i.assignee==='everyone'?i.myPacked:!!i.packed} disabled={!i.assignee||busy} aria-label={`Mark ${i.assignee==='everyone'?'your share of ':''}${i.name} as ${i.packed?'not packed':'packed'}`} onCheckedChange={v=>mutate({action:'packed',id:i.id,packed:!!v},v?'Marked as packed':'Marked as not packed',false)}/><button className="item-name" onClick={()=>editItem(i)}><strong>{i.name}</strong><span>{i.quantity} {i.unit}{i.assignee==='everyone'&&` per person · ${i.quantity*members.length} ${i.unit} total · ${i.packedBy.length}/${members.length} packed`}{i.note&&' · '+i.note}</span></button><div className="item-assignee">{i.assignee?<button className="assignee" onClick={()=>editItem(i)}><span className="mini-avatar">{i.assignee==='everyone'?<Users size={13}/>:members.find(m=>m.id===i.assignee)?.name[0]?.toUpperCase()}</span>{i.assignee==='everyone'?'Everyone':i.assignee===data?.me.id?'You':members.find(m=>m.id===i.assignee)?.name}</button>:<button disabled={busy} className="claim" onClick={()=>mutate({action:'claim',id:i.id},'You’re bringing it',false)}><Plus size={14}/>I’ll bring it</button>}</div><button className="icon-button edit-item" aria-label={`Edit ${i.name}`} onClick={()=>editItem(i)}><Pencil size={15}/></button>{canEdit&&<button className="icon-button delete-item" aria-label={`Delete ${i.name}`} onClick={()=>setDeleting(i)}><Trash2 size={15}/></button>}</div>)}</section>:null})}</div>:<div className="list-empty"><Package size={30}/><h3>{!items.length?'A fresh list, ready for your plans.':'All clear here.'}</h3><p>{!items.length?'Add an item or start with an occasion template.':filter==='unassigned'?'Everyone knows what to bring.':filter==='mine'?'Pick “I’ll bring it” on an unassigned item.':'Items matching this view will appear here.'}</p>{!items.length&&canEdit&&<button className="btn" onClick={()=>{setTemplate(group.occasion==='Custom'?'Camping':group.occasion);show('template')}}>Use a template</button>}</div>}
 {canEdit?<button className="add-row" onClick={()=>editItem()}><Plus size={17}/>Add something to the list</button>:<p className="permission-note">The admin manages this list. You can update assignments and packing status.</p>}</TabsContent><TabsContent value="people"><div className="people-list">{members.map(m=><div className="person" key={m.id}><span className="avatar">{m.name[0]?.toUpperCase()}</span><div><strong>{m.name}{m.id===data?.me.id?' (you)':''}{m.id===group.ownerId?' · Admin':''}</strong><p>{items.filter(i=>i.assignee===m.id||i.assignee==='everyone').length} items assigned · {items.filter(i=>i.assignee==='everyone'?i.packedBy.includes(m.id):i.assignee===m.id&&i.packed).length} packed</p></div></div>)}</div></TabsContent></Tabs></section>
 <aside className="right-rail"><section className="readiness"><div className="section-title"><h3>Coming together</h3><Package size={19}/></div><div className="readiness-number">{percent}<span>% assigned</span></div><Progress value={percent} aria-label="Items assigned"/><p>{unassigned.length?`${unassigned.length} ${unassigned.length===1?'item still needs':'items still need'} someone to bring ${unassigned.length===1?'it':'them'}.`:items.length?'Everything has a person. Time to start packing!':'Add a few essentials to get things moving.'}</p><div className="ready-note"><Check size={16}/>{packed.length} of {items.length} items packed</div></section><section className="rail-card"><span className="eyebrow">BETTER TOGETHER</span><h3>Share the load.</h3><p>Invite your people so everyone can pitch in.</p><button className="btn" onClick={()=>show('invite')}><Link size={16}/>Invite to gathering</button></section>{canEdit&&<button className="template-link" onClick={()=>{setTemplate(group.occasion==='Custom'?'Camping':group.occasion);show('template')}}><Shapes size={21}/><span><strong>Forgot anything?</strong><small>Add essentials from a template</small></span><Plus size={17}/></button>}<div className="sync-note"><RefreshCw size={12}/>Updates automatically every 15 seconds</div></aside></div>
 </>}
 <footer><span className="footer-brand">bringalong.</span><span>Less back-and-forth. More being together.</span></footer>
 </main>
 <Dialog open={!!modal} onOpenChange={v=>{if(!v&&!busy)setModal('')}}><DialogContent className="planner-dialog"><DialogHeader><DialogTitle>{modal==='create'?'Make a plan':modal==='join'?'Join your people':modal==='item'?(item.id?(canEdit?'Edit item':'Update assignment'):'What do we need?'):modal==='invite'?'Good times are better together':modal==='editGroup'?'Edit gathering':'Start with the essentials'}</DialogTitle><DialogDescription>{modal==='create'?'A few details, and you’re ready to bring everyone together.':modal==='join'?'Enter the invite code shared by your group.':modal==='item'?(canEdit?'Add the quantity and choose who’s bringing it.':'Choose who’s bringing this item. Only the admin can edit its details.'):modal==='invite'?'Share this link or code with your people.':modal==='editGroup'?'Keep everyone up to date with the plan.':'These items will be added to your existing list.'}</DialogDescription></DialogHeader>
 {(modal==='create'||modal==='editGroup')&&<form onSubmit={e=>{e.preventDefault();mutate({action:modal==='create'?'create':'editGroup',...groupForm},modal==='create'?'Your gathering is ready':'Gathering updated')}} className="form"><label>Gathering name<input autoFocus required maxLength={120} placeholder="e.g. A weekend at Turkey Point" value={groupForm.name} onChange={e=>setGroupForm({...groupForm,name:e.target.value})}/></label>{modal==='create'&&<label>Occasion<Picker label="Occasion" value={groupForm.occasion} onChange={v=>setGroupForm({...groupForm,occasion:v,prefill:v!=='Custom'})} options={Object.keys(templates).map(t=>({value:t,label:t}))}/></label>}<label>Date <span className="optional">optional</span><input type="date" value={groupForm.date} onChange={e=>setGroupForm({...groupForm,date:e.target.value})}/></label><label>Location <span className="optional">optional</span><input maxLength={120} placeholder="Where are we meeting?" value={groupForm.location} onChange={e=>setGroupForm({...groupForm,location:e.target.value})}/></label><fieldset className="group-settings"><legend>Group settings</legend><label>Members can<Picker label="Member permissions" value={groupForm.memberPermission} onChange={v=>setGroupForm({...groupForm,memberPermission:v})} options={[{value:'edit',label:'Add, edit, and remove items'},{value:'assign',label:'Only update assignments and packing'}]}/></label><p className="subtle">The group creator is the admin and can always manage items and settings.</p><label>Group access<Picker label="Group access" value={groupForm.visibility} onChange={v=>setGroupForm({...groupForm,visibility:v,password:''})} options={[{value:'public',label:'Public — join with a link or code'},{value:'protected',label:'Protected — password required'}]}/></label><p className="subtle">{groupForm.visibility==='public'?'Anyone with site access and the invite can join.':'New members need the invite and group password. Existing members keep access.'}</p>{groupForm.visibility==='protected'&&<label>{modal==='editGroup'&&group?.visibility==='protected'?'New password (leave blank to keep current)':'Group password'}<input type="password" autoComplete="new-password" minLength={8} maxLength={128} required={modal==='create'||group?.visibility!=='protected'} value={groupForm.password} onChange={e=>setGroupForm({...groupForm,password:e.target.value})} placeholder="At least 8 characters"/></label>}</fieldset>{modal==='create'&&groupForm.occasion!=='Custom'&&<label className="check-label"><Checkbox checked={groupForm.prefill} onCheckedChange={v=>setGroupForm({...groupForm,prefill:!!v})}/>Start with {templates[groupForm.occasion].length} {groupForm.occasion.toLowerCase()} essentials</label>}<button className="btn primary full" disabled={busy}>{busy?'Saving…':modal==='create'?'Create gathering':'Save changes'}<ArrowRight size={17}/></button></form>}
 {modal==='join'&&<form className="form" onSubmit={e=>{e.preventDefault();mutate({action:'join',code:joinCode,password:joinPassword},'You’re in!')}}><label>Invite code<input autoFocus required value={joinCode} maxLength={50} onChange={e=>setJoinCode(e.target.value)} placeholder="Paste your invite code" className="code-input"/></label><label>Group password <span className="optional">only for protected groups</span><input type="password" autoComplete="current-password" maxLength={128} value={joinPassword} onChange={e=>setJoinPassword(e.target.value)} placeholder="Leave blank for public groups"/></label><button className="btn primary full" disabled={busy}>{busy?'Joining…':'Join gathering'}<ArrowRight size={17}/></button></form>}
 {modal==='item'&&<form className="form" onSubmit={e=>{e.preventDefault();mutate({action:canEdit?'saveItem':'assign',...item,assignee:item.assignee==='none'?null:item.assignee},item.id?'Item updated':'Added to the list')}}><fieldset disabled={!canEdit} className="item-details"><label>Item name<input autoFocus required maxLength={120} placeholder="e.g. Marinated chicken" value={item.name} onChange={e=>setItem({...item,name:e.target.value})}/></label><div className="form-grid"><label>{item.assignee==='everyone'?'Quantity per person':'Quantity'}<input type="number" min="0.01" max="1000000" step="any" required value={item.quantity} onChange={e=>setItem({...item,quantity:Number(e.target.value)})}/></label><label>Unit<input required maxLength={30} list="units" value={item.unit} onChange={e=>setItem({...item,unit:e.target.value})}/><datalist id="units">{['each','kg','g','L','packs','bags','bottles','cans','sets','servings'].map(v=><option key={v} value={v}/>)}</datalist></label></div><label>Category<Picker label="Category" value={item.category} onChange={v=>setItem({...item,category:v})} options={['Food','Drinks','Equipment','Essentials','Other'].map(v=>({value:v,label:v}))}/></label></fieldset><label>Who’s bringing it?<Picker label="Assignee" value={item.assignee} onChange={v=>setItem({...item,assignee:v})} options={[{value:'none',label:'Unassigned — anyone can volunteer'},{value:'everyone',label:'Everyone — quantity per person'},...members.map(m=>({value:m.id,label:m.name+(m.id===data?.me.id?' (you)':'')}))]}/></label><label>Note <span className="optional">optional</span><input disabled={!canEdit} maxLength={500} placeholder="Anything the group should know?" value={item.note} onChange={e=>setItem({...item,note:e.target.value})}/></label><button className="btn primary full" disabled={busy}>{busy?'Saving…':item.id?'Save changes':'Add to the list'}</button></form>}
 {modal==='invite'&&<div className="form"><div className="invite-code"><span>YOUR GATHERING CODE</span><strong>{group?.code}</strong></div><button className="btn primary full" onClick={copyInvite}><Copy size={17}/>Copy invite link</button><p className="subtle">{group?.visibility==='protected'?'Password-protected: share the password separately with the people you invite.':'Public group: anyone with site access and this code can join.'} {group?.memberPermission==='assign'?'Members can update assignments and packing status.':'Members can add, edit, and remove items.'}</p></div>}
 {modal==='template'&&<div className="form"><Picker label="Occasion template" value={template} onChange={setTemplate} options={['Camping','Party','BBQ','Potluck'].map(t=>({value:t,label:t}))}/><div className="template-preview">{templates[template].map(i=><div key={i.name}><span>{i.name}</span><span>{i.quantity} {i.unit}</span></div>)}</div><p className="subtle">Adds {templates[template].length} unassigned items. Existing items stay as they are.</p><button disabled={busy} className="btn primary full" onClick={()=>mutate({action:'template',occasion:template},'Essentials added')}>{busy?'Adding…':`Add ${templates[template].length} items`}</button></div>}
 {formError&&<p className="form-error" role="alert">{formError}</p>}
 </DialogContent></Dialog>
 <AlertDialog open={!!deleting} onOpenChange={v=>!v&&setDeleting(null)}><AlertDialogContent><AlertDialogTitle>Remove {deleting?.name}?</AlertDialogTitle><AlertDialogDescription>This removes the item from everyone’s list.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Keep item</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={async e=>{e.preventDefault();if(await mutate({action:'deleteItem',id:deleting?.id},'Item removed',false))setDeleting(null)}}>Remove item</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>
}
