import { sqliteTable, text, real, integer, primaryKey, index } from 'drizzle-orm/sqlite-core';
export const gatherings = sqliteTable('gatherings', {id:text('id').primaryKey(),name:text('name').notNull(),occasion:text('occasion').notNull(),date:text('date').notNull().default(''),location:text('location').notNull().default(''),code:text('code').notNull().unique(),createdAt:integer('created_at').notNull(),ownerId:text('owner_id'),memberPermission:text('member_permission').notNull().default('edit'),visibility:text('visibility').notNull().default('public'),passwordHash:text('password_hash')});
export const members = sqliteTable('members',{groupId:text('group_id').notNull().references(()=>gatherings.id,{onDelete:'cascade'}),userId:text('user_id').notNull(),name:text('name').notNull()},t=>[primaryKey({columns:[t.groupId,t.userId]}),index('idx_members_user').on(t.userId)]);
export const items = sqliteTable('items',{id:text('id').primaryKey(),groupId:text('group_id').notNull().references(()=>gatherings.id,{onDelete:'cascade'}),name:text('name').notNull(),quantity:real('quantity').notNull(),unit:text('unit').notNull(),category:text('category').notNull(),assignee:text('assignee'),packed:integer('packed').notNull().default(0),note:text('note').notNull().default(''),createdAt:integer('created_at').notNull()},t=>[index('idx_items_group').on(t.groupId)]);

export const itemPacking = sqliteTable('item_packing',{itemId:text('item_id').notNull().references(()=>items.id,{onDelete:'cascade'}),userId:text('user_id').notNull()},t=>[primaryKey({columns:[t.itemId,t.userId]})]);
export const joinAttempts = sqliteTable('join_attempts',{groupId:text('group_id').notNull().references(()=>gatherings.id,{onDelete:'cascade'}),userId:text('user_id').notNull(),attempts:integer('attempts').notNull().default(0),windowStart:integer('window_start').notNull()},t=>[primaryKey({columns:[t.groupId,t.userId]})]);

export const avatarProfiles = sqliteTable('avatar_profiles',{userId:text('user_id').primaryKey(),avatarText:text('avatar_text').notNull(),color:text('color').notNull()});
